<header>
        <div id="navbar">
            <nav>
                <ul>
                    <li><a href="./">Home</a></li>
                    <li><a href="shop.php">Shop</a></li>
                    <li><a href="about.php">About</a></li>
                </ul>
            </nav>
            <div>
                <button id="burger" aria-label="Menu">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>
            <div>
                <a href="./"><img src="images/logo.webp" alt="Wild Rose Foundry" width="135" height="45"></a>
            </div>
            <menu>
                <!-- **Commented out for later. Need to implement Search Functionality still.**
                <li>
                    <button aria-label="Search">
                        <svg width="24" height="24" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <circle cx="21" cy="21" r="12" stroke="#010001" stroke-width="4"/>
                            <line x1="30" y1="30" x2="42" y2="42" stroke="#010001" stroke-width="4" stroke-linecap="round"/>
                        </svg>
                    </button>
                </li>-->
                <li>
                    <a href="checkout.php" aria-label="Go to Checkout" class="icon-btn">
                        <svg width="28" height="28" viewBox="0 0 48 44" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M6 8H12L16 30H38L42 16H20" stroke="#010001" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
                            <circle cx="20" cy="38" r="3" fill="#010001"/>
                            <circle cx="34" cy="38" r="3" fill="#010001"/>
                        </svg>
                    </a>
                </li>
            </menu>
            <!-- **Commented out for later. Need to implement Search Functionality still.**
            <form action="#" method="post">
                <input type="search" name="search" id="search">
                <button type="submit">
                    <svg width="32" height="32" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <circle cx="21" cy="21" r="12" stroke="#010001" stroke-width="4"/>
                        <line x1="30" y1="30" x2="42" y2="42" stroke="#010001" stroke-width="4" stroke-linecap="round"/>
                    </svg>
                </button>
            </form>-->
        </div>
    </header>